# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appendable', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('changeable', models.BooleanField(default=False)),
                ('deleteable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=20)),
                ('pages', models.SmallIntegerField()),
                ('size', models.CharField(choices=[('840', (('A1', 'A1 578x840'), ('A2', 'A2 420x578'), ('A3', 'A3 289x420'), ('A4', 'A4 210x289'), ('A5', 'A5 140x420'))), ('800', (('A1', 'A1 578x800'), ('A2', 'A2 400x578'), ('A3', 'A3 289x400'), ('A4', 'A4 200x289'), ('A5', 'A5 140x400'))), ('760', (('B2', 'B2 578x760'), ('B3', 'B2 380x578'), ('B4', 'B3 289x380'), ('B5', 'B4 190x289'), ('B6', 'B5 140x380'))), ('700', (('B2', 'B2 578x700'), ('B3', 'B2 350x578'), ('B4', 'B3 289x350'), ('B5', 'B4 175x289'), ('B6', 'B5 140x350')))], default='A3', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistname', models.CharField(max_length=64)),
                ('midlname', models.CharField(max_length=63)),
                ('lastname', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='newspaper',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userslogin.User'),
        ),
        migrations.AddField(
            model_name='acces',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userslogin.NewsPaper'),
        ),
        migrations.AddField(
            model_name='acces',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userslogin.User'),
        ),
    ]
