# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userslogin', '0002_auto_20171203_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone2',
            field=models.CharField(default='', help_text='Номер телефона 2: +38 067 123 44 55', max_length=20),
        ),
        migrations.AlterField(
            model_name='acces',
            name='appendable',
            field=models.BooleanField(default=False, help_text='Разрешение на создание записей'),
        ),
        migrations.AlterField(
            model_name='acces',
            name='changeable',
            field=models.BooleanField(default=False, help_text='Разрешение на редактирование записей'),
        ),
        migrations.AlterField(
            model_name='acces',
            name='deleteable',
            field=models.BooleanField(default=False, help_text='Разрешение на удаление записей'),
        ),
        migrations.AlterField(
            model_name='acces',
            name='target',
            field=models.CharField(choices=[('NewsPaper', 'NewsPaper')], default='NewsPaper', help_text='Выбор таблицы', max_length=120),
        ),
        migrations.AlterField(
            model_name='acces',
            name='visible',
            field=models.BooleanField(default=True, help_text='Разрешение на просмотр записей'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Название департамента', max_length=256),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='manager',
            field=models.ForeignKey(help_text='Менеджер', on_delete=django.db.models.deletion.CASCADE, to='userslogin.User'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='name',
            field=models.CharField(help_text='Название газеты', max_length=128),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='number',
            field=models.CharField(help_text='Номер газеты', max_length=20),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='pages',
            field=models.SmallIntegerField(help_text='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='size',
            field=models.CharField(choices=[('840', (('A1', 'A1 578x840'), ('A2', 'A2 420x578'), ('A3', 'A3 289x420'), ('A4', 'A4 210x289'), ('A5', 'A5 140x420'))), ('800', (('A1', 'A1 578x800'), ('A2', 'A2 400x578'), ('A3', 'A3 289x400'), ('A4', 'A4 200x289'), ('A5', 'A5 140x400'))), ('760', (('B2', 'B2 578x760'), ('B3', 'B2 380x578'), ('B4', 'B3 289x380'), ('B5', 'B4 190x289'), ('B6', 'B5 140x380'))), ('700', (('B2', 'B2 578x700'), ('B3', 'B2 350x578'), ('B4', 'B3 289x350'), ('B5', 'B4 175x289'), ('B6', 'B5 140x350')))], default='A3', help_text='Формат газеты', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False, help_text='Разрешить доступ к системе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dep',
            field=models.ForeignKey(help_text='Департамент', null=True, on_delete=django.db.models.deletion.CASCADE, to='userslogin.Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fistname',
            field=models.CharField(default='', help_text='Имя', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='func',
            field=models.CharField(default='', help_text='Должность', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='', help_text='Фамилия', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='midlname',
            field=models.CharField(default='', help_text='Отчество', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(help_text='Логин', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Пароль', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone1',
            field=models.CharField(default='', help_text='Номер телефона 1: +38 067 123 44 55', max_length=20),
        ),
    ]
