# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userslogin', '0003_auto_20171203_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', help_text='Марка бумаги', max_length=64)),
                ('width', models.SmallIntegerField(default=84, help_text='Ширина роля (см)')),
                ('density', models.SmallIntegerField(default=42, help_text='Плотность бумаги (г/м.кв)')),
            ],
        ),
        migrations.AddField(
            model_name='newspaper',
            name='copies',
            field=models.IntegerField(default=0, help_text='Тираж'),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='copiesadd',
            field=models.IntegerField(default=0, help_text='Тираж'),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='createdatetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата/Время внесения записи о газете'),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='filedate',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата прихода файлов', null=True),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='filetime',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Время прихода файлов', null=True),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='pages1color',
            field=models.CharField(default='', help_text='Список ч/б страниц (например: 3, 4, 5, 6)', max_length=260),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='pages2color',
            field=models.CharField(default='', help_text='Список двухцветных страниц (например: 2, 7)', max_length=260),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='pages4color',
            field=models.CharField(default='', help_text='Список полноцветных страниц (например: 1, 8)', max_length=260),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='shipmentdate',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата отгрузки готовой продукции', null=True),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='shipmenttime',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Время отгрузки готовой продукции', null=True),
        ),
        migrations.AlterField(
            model_name='acces',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, to='userslogin.User'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='name',
            field=models.CharField(default='', help_text='Название газеты', max_length=128),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='number',
            field=models.CharField(default='', help_text='Номер газеты', max_length=20),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='pages',
            field=models.SmallIntegerField(default=0, help_text='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='size',
            field=models.CharField(choices=[('840', (('A1', 'A1 578x840'), ('A2', 'A2 420x578'), ('A3', 'A3 289x420'), ('A4', 'A4 210x289'), ('A5', 'A5 140x420'))), ('800', (('A1', 'A1 578x800'), ('A2', 'A2 400x578'), ('A3', 'A3 289x400'), ('A4', 'A4 200x289'), ('A5', 'A5 140x400'))), ('760', (('B2', 'B2 578x760'), ('B3', 'B3 380x578'), ('B4', 'B4 289x380'), ('B5', 'B5 190x289'), ('B6', 'B6 140x380'))), ('700', (('B2', 'B2 578x700'), ('B3', 'B3 350x578'), ('B4', 'B4 289x350'), ('B5', 'B5 175x289'), ('B6', 'B6 140x350')))], default='A3', help_text='Формат газеты', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='e-mail', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='papermarks',
            field=models.ForeignKey(help_text='Тип бумаги', null=True, on_delete=django.db.models.deletion.CASCADE, to='userslogin.Paper'),
        ),
    ]
